version: "3"
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
    volumes:
    - postgres:/var/lib/postgresql/data

volumes:
  postgres:
